version: 0.2

env:
    variables:
        BRANCH_NAME: "master"
        MAJOR_VERSION: "1"
        MINOR_VERSION: "0"
        GIT_REPO: "https://github.com/charvee11/myapp.git"
        GIT_USER: "charvee11"
        GIT_PASS: "Sarita@1964"
phases:
  build:
    commands:
      - echo Build started on `date`
      - bash git_tagging.sh
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/myapp-1.0-SNAPSHOT.jar
