version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - bash git_tagging.sh
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/myapp-1.0-SNAPSHOT.jar
