version: 0.2

env:
    variables:
        BRANCH_NAME: "master"
        MAJOR_VERSION: "1"
        MINOR_VERSION: "0"
        GIT_REPO: "ssh:git@github.com:charvee11/myapp.git"
        
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
      - bash git_tagging.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/myapp-1.0-SNAPSHOT.jar